package com.ttl.tabletennis.service;

import com.ttl.tabletennis.dto.MetricDefinitionDto;
import org.springframework.stereotype.Service;

import java.util.List;

/** Canonical language for prices, quality metrics, ratings, and model signals. */
@Service
public class MetricGlossaryService {
    private static final String VERSION = "research-glossary-v1";
    private static final List<MetricDefinitionDto> DEFINITIONS = List.of(
            metric("raw_implied_probability", "MARKET", "Book break-even chance", "Raw implied probability", "The win rate required to break even at the displayed price before removing the book margin.", "1 / decimal odds", "Higher means the book price treats that side as more likely.", "probability", "One paired two-way market", List.of("The two raw sides normally sum above 100% because of sportsbook hold."), List.of("no_vig_probability", "market_overround")),
            metric("no_vig_probability", "MARKET", "Market fair chance", "Paired-market no-vig probability", "The sportsbook's relative opinion after its two-way margin is removed.", "side implied probability / sum of both implied probabilities", "Compare this with model probability to study disagreement; do not treat it as a tradable price.", "probability", "One fresh paired market", List.of("Requires both sides from the same book and observation window."), List.of("raw_implied_probability", "model_market_gap")),
            metric("market_overround", "MARKET", "Book margin", "Market hold / overround", "How far the two raw implied probabilities add above 100%.", "p(raw side 1) + p(raw side 2) - 1", "Higher means a more expensive market for the bettor.", "percentage points", "One fresh paired market", List.of("It is not the book's realized profit."), List.of("raw_implied_probability", "fair_odds")),
            metric("fair_odds", "MARKET", "Our fair price", "Model fair odds", "The no-margin price implied by the model's frozen win probability.", "decimal = 1 / model probability; converted to American odds", "Shorter negative odds mean higher model win probability.", "American odds", "One frozen model call", List.of("Fair odds are not an executable offer and do not include sportsbook hold."), List.of("model_probability", "model_price_at_book_margin")),
            metric("model_price_at_book_margin", "MARKET", "Our price with book margin", "Model price at observed overround", "The model probability translated into a two-way price using the same margin seen at Hard Rock, making visual price comparison like-for-like.", "model fair probabilities re-scaled by observed market overround", "Closer to Hard Rock means less disagreement after equalizing margin presentation.", "American odds", "One fresh paired market", List.of("This display does not change executable edge; it is a comparison aid."), List.of("fair_odds", "market_overround")),
            metric("model_market_gap", "MARKET", "Model vs market gap", "Model-minus-no-vig market gap", "The model's frozen win probability minus the book's paired no-vig probability for the same side.", "model probability - no-vig market probability", "Positive means the model is more optimistic than the de-margined market.", "percentage points", "30 resolved calls per band; 100 preferred", List.of("Disagreement is evidence to investigate, not proof of value."), List.of("expected_value", "rating_agreement")),
            metric("expected_value", "PORTFOLIO", "Expected return", "Price-specific expected value", "The model-weighted expected net return at the executable price.", "p(win) × net win payout - p(loss) × stake", "Positive is required before a value policy should act.", "return per unit staked", "100 priced resolved calls; effective sample also shown", List.of("Sensitive to model calibration and captured-price freshness."), List.of("model_market_gap", "flat_stake_roi")),
            metric("accuracy", "QUALITY", "Winner accuracy", "Directional accuracy", "The share of trusted resolved model leans whose predicted winner won.", "correct directional calls / trusted resolved directional calls", "Higher is better, but must be read beside probability calibration and the market benchmark.", "percent", "100 outcomes for direction; more for narrow differences", List.of("Unresolved, void, non-binary, and no-lean calls are excluded."), List.of("brier_score", "effective_sample_size")),
            metric("brier_score", "QUALITY", "Probability error", "Brier score", "Squared error of each frozen win probability against the binary result, averaged across eligible outcomes.", "mean((predicted probability - outcome)²)", "Lower is better; 0 is perfect.", "score 0–1", "100 trusted probabilities; show bins and uncertainty", List.of("Accuracy alone cannot reveal probability calibration."), List.of("accuracy", "ece")),
            metric("log_loss", "QUALITY", "Confidence penalty", "Log loss", "Probability error that penalizes confident wrong predictions especially strongly.", "mean(-y log(p) - (1-y) log(1-p))", "Lower is better.", "score", "100 trusted probabilities", List.of("Near-zero or near-one probabilities dominate the metric."), List.of("brier_score", "ece")),
            metric("ece", "QUALITY", "Calibration gap", "Expected calibration error", "Weighted average distance between stated probability and observed win rate across probability bins.", "sum(bin share × |mean predicted - observed rate|)", "Lower is better.", "probability", "At least 20 per displayed bin; merge sparse bins", List.of("The value depends on binning, so the bin definition is versioned."), List.of("brier_score", "effective_sample_size")),
            metric("flat_stake_roi", "QUALITY", "$1 return", "Flat-$1 ROI", "Hypothetical return from one dollar on every priced model lean in the selected cohort.", "sum(flat-stake profit) / count(priced resolved leans)", "Positive means the captured prices would have returned a profit before real-world frictions.", "percent", "100 priced outcomes; cluster interval preferred", List.of("It is a research benchmark, not the official policy record."), List.of("expected_value", "closing_line_value")),
            metric("closing_line_value", "QUALITY", "Price improvement", "Closing-line value", "Difference between the captured price and the versioned close definition for the same side and source.", "captured implied probability compared with closing implied probability", "Consistently beating the close is favorable.", "percentage points", "100 covered closes", List.of("Coverage and exact close timestamp must be shown."), List.of("flat_stake_roi", "market_overround")),
            metric("effective_sample_size", "QUALITY", "Independent evidence", "Effective sample size", "A cluster-aware estimate of how much independent information remains after repeated players and matchups are accounted for.", "versioned cluster/bootstrap estimator", "Higher means evidence is less concentrated.", "effective outcomes", "50 effective observations before adaptive conclusions", List.of("It can be much lower than the raw number of calls."), List.of("accuracy", "sample_readiness")),
            metric("elo", "RATING", "Elo strength", "Elo rating", "A sequential strength rating updated from prior wins, losses, and opponent strength.", "versioned Elo update", "Higher means stronger estimated player skill.", "rating points", "20 matches is early; 50 is useful", List.of("Does not explicitly model uncertainty."), List.of("glicko", "rating_agreement")),
            metric("glicko", "RATING", "Glicko strength", "Glicko-2 rating / RD / volatility", "A strength estimate paired with uncertainty and volatility, so inactive or thin players remain visibly uncertain.", "Glicko-2 versioned update", "Higher rating is stronger; lower RD is more certain.", "rating / deviation", "10 matches minimum; interpret RD", List.of("A high rating with high RD is not high-confidence evidence."), List.of("elo", "trueskill2")),
            metric("trueskill2", "RATING", "TrueSkill strength", "TrueSkill2", "A Bayesian skill estimate that carries both mean strength and uncertainty.", "versioned TrueSkill2 update", "Higher mean and lower sigma indicate stronger, more certain evidence.", "mu / sigma", "10 matches minimum; interpret sigma", List.of("Scale is not directly comparable with Elo."), List.of("glicko", "rating_agreement")),
            metric("recent_form", "SIGNAL", "Recent record", "Recent form delta", "Difference in recent win performance at the point in time of the call.", "versioned recency-weighted win-rate difference", "Positive favors player one in the stored feature orientation.", "normalized contribution", "10 recent matches; 50 for stability", List.of("Raw recent record can reflect opponent quality."), List.of("opponent_adjusted_form", "schedule_strength")),
            metric("opponent_adjusted_form", "SIGNAL", "Opponent-adjusted form", "Opponent-adjusted form delta", "Recent performance adjusted for the strength of opponents faced.", "versioned residual/strength adjustment", "Positive favors player one.", "normalized contribution", "30 matches across involved players", List.of("Depends on rating and identity coverage."), List.of("recent_form", "schedule_strength")),
            metric("h2h_decay", "SIGNAL", "Recent head-to-head", "Head-to-Head (Decayed)", "Direct meetings weighted so recent encounters count more than old ones.", "time-decayed direct-match outcome difference", "Positive favors player one; near zero means little direct evidence.", "normalized contribution", "5 direct meetings is still thin; 10 is useful", List.of("Repeated matchup samples are highly correlated and need cluster-aware inference."), List.of("recent_form", "effective_sample_size")),
            metric("rating_agreement", "SIGNAL", "Rating agreement", "Rater ensemble agreement", "How consistently Elo, Glicko, TrueSkill2, Weng-Lin, and the ensemble point in the same direction.", "versioned agreement score across independent raters", "Higher means the rating systems agree on direction.", "percent", "One call, validated over 100 outcomes", List.of("Agreement can be confidently wrong when every rating shares missing data."), List.of("elo", "glicko", "trueskill2")),
            metric("uncertainty_width", "SIGNAL", "Probability uncertainty", "Confidence interval width", "Width of the model's frozen probability interval for the selected side.", "upper probability bound - lower probability bound", "Narrower usually means more precise evidence.", "percentage points", "One call; validate coverage over 100 outcomes", List.of("A narrow interval is useful only if empirical coverage is calibrated."), List.of("brier_score", "rating_agreement")),
            metric("signal_quality", "SIGNAL", "Signal quality", "Signal-quality composite", "A versioned summary of evidence depth, reliability, agreement, and uncertainty used by policy gates.", "versioned weighted composite recorded with the call", "Higher is stronger, subject to explicit minimum gates.", "score 0–1", "100 resolved calls by band", List.of("Always inspect its components; a composite must not hide one weak input."), List.of("rating_agreement", "uncertainty_width")),
            metric("sample_readiness", "QUALITY", "Evidence readiness", "Sample-confidence readiness", "Progress toward predeclared raw and effective sample targets; it is not a performance score.", "minimum of relevant raw/effective coverage targets", "Higher means conclusions deserve more weight.", "percent", "100 raw directional and 50 effective observations", List.of("A fully ready sample can still show poor performance."), List.of("effective_sample_size", "accuracy"))
    );

    public List<MetricDefinitionDto> all() { return DEFINITIONS; }

    private static MetricDefinitionDto metric(String key, String category, String userLabel, String adminLabel,
                                              String summary, String formula, String directionality, String unit,
                                              String minimumSample, List<String> caveats, List<String> related) {
        return new MetricDefinitionDto(key, category, userLabel, adminLabel, summary, formula, directionality,
                unit, minimumSample, caveats, related, VERSION);
    }
}
