package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Locale;

/** Immutable replay definitions and their frozen event receipts. */
public class V20260817003__historical_replay_lab extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        if (!tableExists(context.getConnection().getMetaData(), "paper_trade_model_call")) return;
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS replay_definition (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        parent_replay_id BIGINT,
                        label VARCHAR(160) NOT NULL,
                        status VARCHAR(24) NOT NULL,
                        replay_mode VARCHAR(40) NOT NULL,
                        source_run_ids VARCHAR(1000) NOT NULL,
                        window_start TIMESTAMP,
                        window_end TIMESTAMP,
                        capture_rule VARCHAR(80) NOT NULL,
                        model_lane_keys VARCHAR(600) NOT NULL,
                        portfolio_keys VARCHAR(600) NOT NULL,
                        execution_book VARCHAR(32) NOT NULL,
                        initial_bankroll DOUBLE NOT NULL,
                        max_quote_age_seconds INT NOT NULL,
                        deterministic_seed BIGINT NOT NULL,
                        definition_checksum VARCHAR(64) NOT NULL,
                        leakage_audit_status VARCHAR(40) NOT NULL,
                        reproducible BOOLEAN NOT NULL,
                        event_count INT NOT NULL,
                        resolved_count INT NOT NULL,
                        priced_resolved_count INT NOT NULL,
                        correct_count INT NOT NULL,
                        flat_stake_pnl DOUBLE NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        started_at TIMESTAMP,
                        completed_at TIMESTAMP,
                        CONSTRAINT uk_replay_definition_checksum UNIQUE (definition_checksum),
                        CONSTRAINT fk_replay_parent FOREIGN KEY (parent_replay_id)
                            REFERENCES replay_definition(id)
                    )
                    """);
            statement.execute("CREATE INDEX IF NOT EXISTS idx_replay_definition_created ON replay_definition(created_at)");
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS replay_event_log (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        replay_id BIGINT NOT NULL,
                        sequence_number INT NOT NULL,
                        source_run_id BIGINT NOT NULL,
                        source_call_id BIGINT NOT NULL,
                        event_time TIMESTAMP NOT NULL,
                        event_type VARCHAR(32) NOT NULL,
                        event_name VARCHAR(220),
                        capture_type VARCHAR(24),
                        predicted_winner_name VARCHAR(180),
                        model_probability DOUBLE,
                        hard_rock_american_odds INT,
                        decision_status VARCHAR(32),
                        pipeline_stage VARCHAR(40),
                        effective_outcome VARCHAR(24),
                        outcome_source VARCHAR(32),
                        flat_stake_profit DOUBLE,
                        CONSTRAINT uk_replay_event_sequence UNIQUE (replay_id, sequence_number),
                        CONSTRAINT uk_replay_event_call UNIQUE (replay_id, source_call_id),
                        CONSTRAINT fk_replay_event_definition FOREIGN KEY (replay_id)
                            REFERENCES replay_definition(id),
                        CONSTRAINT fk_replay_event_source_call FOREIGN KEY (source_call_id)
                            REFERENCES paper_trade_model_call(id)
                    )
                    """);
            statement.execute("CREATE INDEX IF NOT EXISTS idx_replay_event_time ON replay_event_log(replay_id, event_time)");
        }
    }

    private static boolean tableExists(DatabaseMetaData metadata, String tableName) throws Exception {
        for (String candidate : new String[]{tableName, tableName.toUpperCase(Locale.ROOT), tableName.toLowerCase(Locale.ROOT)}) {
            try (ResultSet rows = metadata.getTables(null, null, candidate, new String[]{"TABLE"})) {
                if (rows.next()) return true;
            }
        }
        return false;
    }
}
