package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Locale;

/**
 * Research-grade opportunity, model-lane, portfolio, annotation, and
 * experiment identities. Polling refreshes update a frozen opportunity/lane
 * row; they never create additional statistical samples.
 */
public class V20260817001__research_run_foundation extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        // Legacy Flyway-only bootstrap tests intentionally omit Hibernate-owned
        // operational tables. On a real application schema these tables are
        // present before this upgrade; a fresh empty app lets Hibernate create
        // the mapped research entities after Flyway completes.
        if (!tableExists(connection.getMetaData(), "paper_trade_session")
                || !tableExists(connection.getMetaData(), "paper_trade_model_call")) {
            return;
        }
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS decision_opportunity (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        event_key VARCHAR(320) NOT NULL,
                        external_event_id VARCHAR(160),
                        source_feed_event_id VARCHAR(160),
                        event_name VARCHAR(220),
                        competition_name VARCHAR(180),
                        player1_id BIGINT,
                        player2_id BIGINT,
                        start_time_iso VARCHAR(80),
                        capture_type VARCHAR(24) NOT NULL,
                        first_observed_at TIMESTAMP NOT NULL,
                        frozen_at TIMESTAMP,
                        match_id_high_watermark BIGINT,
                        CONSTRAINT uk_decision_opportunity_session_event UNIQUE (session_id, event_key),
                        CONSTRAINT fk_decision_opportunity_session FOREIGN KEY (session_id)
                            REFERENCES paper_trade_session(id)
                    )
                    """);
            statement.execute("CREATE INDEX IF NOT EXISTS idx_decision_opportunity_session_time ON decision_opportunity(session_id, first_observed_at)");
            statement.execute("CREATE INDEX IF NOT EXISTS idx_decision_opportunity_external ON decision_opportunity(external_event_id)");

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS run_model_lane_definition (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        lane_key VARCHAR(64) NOT NULL,
                        display_name VARCHAR(100) NOT NULL,
                        lane_role VARCHAR(24) NOT NULL,
                        ordinal_position INT NOT NULL,
                        model_family VARCHAR(64),
                        model_version VARCHAR(100),
                        artifact_checksum VARCHAR(64),
                        feature_schema_checksum VARCHAR(64),
                        calibration_id VARCHAR(100),
                        enabled BOOLEAN NOT NULL,
                        primary_lane BOOLEAN NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_run_model_lane_session_key UNIQUE (session_id, lane_key),
                        CONSTRAINT fk_run_model_lane_session FOREIGN KEY (session_id)
                            REFERENCES paper_trade_session(id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS run_model_lane_evaluation (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        opportunity_id BIGINT NOT NULL,
                        lane_definition_id BIGINT NOT NULL,
                        source_model_call_id BIGINT,
                        captured_at TIMESTAMP NOT NULL,
                        player1_probability DOUBLE,
                        player2_probability DOUBLE,
                        predicted_winner_player_id BIGINT,
                        predicted_winner_name VARCHAR(180),
                        raw_probability DOUBLE,
                        confidence_low DOUBLE,
                        confidence_high DOUBLE,
                        fair_american_odds INT,
                        selection_score DOUBLE,
                        signal_quality DOUBLE,
                        top_trigger VARCHAR(180),
                        feature_contributions VARCHAR(2400),
                        CONSTRAINT uk_lane_evaluation_opportunity_lane UNIQUE (opportunity_id, lane_definition_id),
                        CONSTRAINT fk_lane_evaluation_opportunity FOREIGN KEY (opportunity_id)
                            REFERENCES decision_opportunity(id),
                        CONSTRAINT fk_lane_evaluation_definition FOREIGN KEY (lane_definition_id)
                            REFERENCES run_model_lane_definition(id),
                        CONSTRAINT fk_lane_evaluation_call FOREIGN KEY (source_model_call_id)
                            REFERENCES paper_trade_model_call(id)
                    )
                    """);
            statement.execute("CREATE INDEX IF NOT EXISTS idx_lane_evaluation_lane_time ON run_model_lane_evaluation(lane_definition_id, captured_at)");

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS run_portfolio_definition (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        portfolio_key VARCHAR(64) NOT NULL,
                        display_name VARCHAR(100) NOT NULL,
                        portfolio_type VARCHAR(32) NOT NULL,
                        model_lane_key VARCHAR(64),
                        policy_version VARCHAR(100),
                        policy_json VARCHAR(4000),
                        enabled BOOLEAN NOT NULL,
                        primary_portfolio BOOLEAN NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_run_portfolio_session_key UNIQUE (session_id, portfolio_key),
                        CONSTRAINT fk_run_portfolio_session FOREIGN KEY (session_id)
                            REFERENCES paper_trade_session(id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS run_portfolio_decision (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        opportunity_id BIGINT NOT NULL,
                        portfolio_definition_id BIGINT NOT NULL,
                        lane_evaluation_id BIGINT,
                        decision_status VARCHAR(32) NOT NULL,
                        decision_reason VARCHAR(180),
                        selected_player_id BIGINT,
                        selected_player_name VARCHAR(180),
                        model_probability DOUBLE,
                        market_probability DOUBLE,
                        edge_value DOUBLE,
                        american_odds INT,
                        virtual_stake DOUBLE,
                        captured_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_portfolio_decision_opportunity_portfolio UNIQUE (opportunity_id, portfolio_definition_id),
                        CONSTRAINT fk_portfolio_decision_opportunity FOREIGN KEY (opportunity_id)
                            REFERENCES decision_opportunity(id),
                        CONSTRAINT fk_portfolio_decision_definition FOREIGN KEY (portfolio_definition_id)
                            REFERENCES run_portfolio_definition(id),
                        CONSTRAINT fk_portfolio_decision_lane_eval FOREIGN KEY (lane_evaluation_id)
                            REFERENCES run_model_lane_evaluation(id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS run_benchmark_evaluation (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        opportunity_id BIGINT NOT NULL,
                        benchmark_key VARCHAR(64) NOT NULL,
                        selected_player_id BIGINT,
                        selected_player_name VARCHAR(180),
                        probability DOUBLE,
                        american_odds INT,
                        source_code VARCHAR(64),
                        captured_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_benchmark_opportunity_key UNIQUE (opportunity_id, benchmark_key),
                        CONSTRAINT fk_benchmark_opportunity FOREIGN KEY (opportunity_id)
                            REFERENCES decision_opportunity(id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS run_annotation (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        target_type VARCHAR(32) NOT NULL,
                        target_id VARCHAR(160),
                        annotation_text VARCHAR(2000) NOT NULL,
                        tags VARCHAR(600),
                        author VARCHAR(80) NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_run_annotation_session FOREIGN KEY (session_id)
                            REFERENCES paper_trade_session(id)
                    )
                    """);
            statement.execute("CREATE INDEX IF NOT EXISTS idx_run_annotation_session_time ON run_annotation(session_id, created_at)");

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS experiment_collection (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(140) NOT NULL,
                        description VARCHAR(2000),
                        hypothesis VARCHAR(2000),
                        status VARCHAR(32) NOT NULL,
                        created_by VARCHAR(80) NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL
                    )
                    """);

            statement.execute("""
                    CREATE TABLE IF NOT EXISTS experiment_run_link (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        experiment_id BIGINT NOT NULL,
                        session_id BIGINT NOT NULL,
                        role VARCHAR(32) NOT NULL,
                        note VARCHAR(1000),
                        linked_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_experiment_run UNIQUE (experiment_id, session_id),
                        CONSTRAINT fk_experiment_run_experiment FOREIGN KEY (experiment_id)
                            REFERENCES experiment_collection(id),
                        CONSTRAINT fk_experiment_run_session FOREIGN KEY (session_id)
                            REFERENCES paper_trade_session(id)
                    )
                    """);
            backfillHistoricalResearchGraph(statement);
        }
    }

    private static void backfillHistoricalResearchGraph(Statement statement) throws Exception {
        statement.executeUpdate("""
                INSERT INTO decision_opportunity (
                    session_id, event_key, external_event_id, source_feed_event_id, event_name,
                    competition_name, player1_id, player2_id, start_time_iso, capture_type,
                    first_observed_at, frozen_at, match_id_high_watermark)
                SELECT c.session_id, c.event_key, c.external_event_id, c.source_feed_event_id, c.event_name,
                    c.competition_name, c.player1_id, c.player2_id, c.start_time_iso, c.capture_type,
                    c.captured_at,
                    CASE WHEN c.capture_type = 'PREMATCH_CLOSE' THEN c.captured_at ELSE NULL END,
                    c.match_id_high_watermark
                FROM paper_trade_model_call c
                WHERE NOT EXISTS (
                    SELECT 1 FROM decision_opportunity o
                    WHERE o.session_id = c.session_id AND o.event_key = c.event_key)
                """);
        statement.executeUpdate("""
                INSERT INTO run_model_lane_definition (
                    session_id, lane_key, display_name, lane_role, ordinal_position, model_family,
                    model_version, artifact_checksum, feature_schema_checksum, calibration_id,
                    enabled, primary_lane, created_at)
                SELECT s.id, 'CHAMPION', 'Champion', 'CHAMPION', 0, s.effective_model_family,
                    COALESCE(s.effective_model_version,
                        (SELECT MAX(c.model_version) FROM paper_trade_model_call c WHERE c.session_id = s.id)),
                    s.effective_artifact_checksum, s.feature_schema_checksum, s.calibration_id,
                    TRUE, TRUE, s.created_at
                FROM paper_trade_session s
                WHERE EXISTS (SELECT 1 FROM paper_trade_model_call c WHERE c.session_id = s.id)
                  AND NOT EXISTS (SELECT 1 FROM run_model_lane_definition l
                                  WHERE l.session_id = s.id AND l.lane_key = 'CHAMPION')
                """);
        statement.executeUpdate("""
                INSERT INTO run_model_lane_evaluation (
                    opportunity_id, lane_definition_id, source_model_call_id, captured_at,
                    player1_probability, player2_probability, predicted_winner_player_id,
                    predicted_winner_name, raw_probability, confidence_low, confidence_high,
                    fair_american_odds, selection_score, signal_quality, top_trigger, feature_contributions)
                SELECT o.id, l.id, c.id, c.captured_at,
                    CASE WHEN c.predicted_winner_player_id = c.player1_id THEN c.model_probability
                         WHEN c.predicted_winner_player_id = c.player2_id THEN 1.0 - c.model_probability END,
                    CASE WHEN c.predicted_winner_player_id = c.player2_id THEN c.model_probability
                         WHEN c.predicted_winner_player_id = c.player1_id THEN 1.0 - c.model_probability END,
                    c.predicted_winner_player_id, c.predicted_winner_name, c.raw_model_probability,
                    c.confidence_low, c.confidence_high, c.model_fair_american_odds,
                    c.selection_score, c.signal_quality, c.top_trigger, c.feature_contributions
                FROM paper_trade_model_call c
                JOIN decision_opportunity o ON o.session_id = c.session_id AND o.event_key = c.event_key
                JOIN run_model_lane_definition l ON l.session_id = c.session_id AND l.lane_key = 'CHAMPION'
                WHERE NOT EXISTS (SELECT 1 FROM run_model_lane_evaluation e
                                  WHERE e.opportunity_id = o.id AND e.lane_definition_id = l.id)
                """);
        statement.executeUpdate("""
                INSERT INTO run_portfolio_definition (
                    session_id, portfolio_key, display_name, portfolio_type, model_lane_key,
                    policy_version, policy_json, enabled, primary_portfolio, created_at)
                SELECT s.id, p.portfolio_key, p.display_name, p.portfolio_type, 'CHAMPION',
                    s.policy_version, '{"frozen":true,"source":"historical-session"}',
                    TRUE, p.primary_portfolio, s.created_at
                FROM paper_trade_session s
                CROSS JOIN (SELECT 'CHAMPION_STRICT' portfolio_key, 'Champion Strict' display_name,
                                   'POLICY' portfolio_type, TRUE primary_portfolio
                            UNION ALL
                            SELECT 'ALL_CALLS', 'All Model Leans', 'RESEARCH', FALSE) p
                WHERE EXISTS (SELECT 1 FROM paper_trade_model_call c WHERE c.session_id = s.id)
                  AND NOT EXISTS (SELECT 1 FROM run_portfolio_definition d
                                  WHERE d.session_id = s.id AND d.portfolio_key = p.portfolio_key)
                """);
        statement.executeUpdate("""
                INSERT INTO run_portfolio_decision (
                    opportunity_id, portfolio_definition_id, lane_evaluation_id, decision_status,
                    decision_reason, selected_player_id, selected_player_name, model_probability,
                    market_probability, edge_value, american_odds, virtual_stake, captured_at)
                SELECT o.id, p.id, e.id, c.decision_status, c.decision_reason,
                    NULL, NULL, NULL, NULL, c.suggested_edge, NULL,
                    CASE WHEN UPPER(c.decision_status) = 'PLACED' THEN 1.0 ELSE 0.0 END, c.captured_at
                FROM paper_trade_model_call c
                JOIN decision_opportunity o ON o.session_id = c.session_id AND o.event_key = c.event_key
                JOIN run_model_lane_definition l ON l.session_id = c.session_id AND l.lane_key = 'CHAMPION'
                JOIN run_model_lane_evaluation e ON e.opportunity_id = o.id AND e.lane_definition_id = l.id
                JOIN run_portfolio_definition p ON p.session_id = c.session_id AND p.portfolio_key = 'CHAMPION_STRICT'
                WHERE NOT EXISTS (SELECT 1 FROM run_portfolio_decision d
                                  WHERE d.opportunity_id = o.id AND d.portfolio_definition_id = p.id)
                """);
        statement.executeUpdate("""
                INSERT INTO run_portfolio_decision (
                    opportunity_id, portfolio_definition_id, lane_evaluation_id, decision_status,
                    decision_reason, selected_player_id, selected_player_name, model_probability,
                    market_probability, edge_value, american_odds, virtual_stake, captured_at)
                SELECT o.id, p.id, e.id,
                    CASE WHEN c.predicted_winner_player_id IS NULL THEN 'NO_LEAN' ELSE 'TRACKED' END,
                    'EVERY_FROZEN_MODEL_CALL', c.predicted_winner_player_id, c.predicted_winner_name,
                    c.model_probability, c.hard_rock_no_vig_probability, c.suggested_edge,
                    c.hard_rock_american_odds,
                    CASE WHEN c.predicted_winner_player_id IS NULL THEN 0.0 ELSE 1.0 END, c.captured_at
                FROM paper_trade_model_call c
                JOIN decision_opportunity o ON o.session_id = c.session_id AND o.event_key = c.event_key
                JOIN run_model_lane_definition l ON l.session_id = c.session_id AND l.lane_key = 'CHAMPION'
                JOIN run_model_lane_evaluation e ON e.opportunity_id = o.id AND e.lane_definition_id = l.id
                JOIN run_portfolio_definition p ON p.session_id = c.session_id AND p.portfolio_key = 'ALL_CALLS'
                WHERE NOT EXISTS (SELECT 1 FROM run_portfolio_decision d
                                  WHERE d.opportunity_id = o.id AND d.portfolio_definition_id = p.id)
                """);
        statement.executeUpdate("""
                INSERT INTO run_benchmark_evaluation (
                    opportunity_id, benchmark_key, selected_player_id, selected_player_name,
                    probability, american_odds, source_code, captured_at)
                SELECT o.id, 'HARD_ROCK_FAVORITE',
                    CASE WHEN c.opponent_hard_rock_american_odds < c.hard_rock_american_odds
                         THEN CASE WHEN c.predicted_winner_player_id = c.player1_id THEN c.player2_id ELSE c.player1_id END
                         ELSE c.predicted_winner_player_id END,
                    CASE WHEN c.opponent_hard_rock_american_odds < c.hard_rock_american_odds
                         THEN CASE WHEN c.predicted_winner_player_id = c.player1_id THEN c.player2_name ELSE c.player1_name END
                         ELSE c.predicted_winner_name END,
                    CASE WHEN c.opponent_hard_rock_american_odds < c.hard_rock_american_odds
                         THEN 1.0 - c.hard_rock_no_vig_probability ELSE c.hard_rock_no_vig_probability END,
                    CASE WHEN c.opponent_hard_rock_american_odds < c.hard_rock_american_odds
                         THEN c.opponent_hard_rock_american_odds ELSE c.hard_rock_american_odds END,
                    'HARD_ROCK', c.captured_at
                FROM paper_trade_model_call c
                JOIN decision_opportunity o ON o.session_id = c.session_id AND o.event_key = c.event_key
                WHERE c.hard_rock_american_odds IS NOT NULL
                  AND NOT EXISTS (SELECT 1 FROM run_benchmark_evaluation b
                                  WHERE b.opportunity_id = o.id AND b.benchmark_key = 'HARD_ROCK_FAVORITE')
                """);
    }

    private static boolean tableExists(DatabaseMetaData metadata, String table) throws Exception {
        for (String candidate : new String[]{table, table.toUpperCase(Locale.ROOT), table.toLowerCase(Locale.ROOT)}) {
            try (ResultSet rows = metadata.getTables(null, null, candidate, new String[]{"TABLE"})) {
                while (rows.next()) {
                    if (table.equalsIgnoreCase(rows.getString("TABLE_NAME"))) return true;
                }
            }
        }
        return false;
    }
}
