package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Statement;

/** Registry metadata that distinguishes executable books from references. */
public class V20260817002__market_book_registry extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS market_book (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        source_code VARCHAR(32) NOT NULL,
                        display_name VARCHAR(100) NOT NULL,
                        market_role VARCHAR(24) NOT NULL,
                        authorized BOOLEAN NOT NULL,
                        enabled BOOLEAN NOT NULL,
                        consensus_weight DOUBLE NOT NULL,
                        notes VARCHAR(600),
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_market_book_source UNIQUE (source_code)
                    )
                    """);
            statement.executeUpdate("""
                    INSERT INTO market_book (source_code, display_name, market_role, authorized, enabled,
                                             consensus_weight, notes, created_at, updated_at)
                    SELECT 'HR_MKT', 'Hard Rock Bet', 'EXECUTABLE', TRUE, TRUE, 1.0,
                           'Primary Florida execution reference', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (SELECT 1 FROM market_book WHERE source_code = 'HR_MKT')
                    """);
        }
    }
}
