package com.ttl.tabletennis.dto;

public record LiveOddsRecommendationDto(String source,
                                        String strategy,
                                        String modelVersion,
                                        String eventName,
                                        String competitionName,
                                        boolean live,
                                        String startTimeIso,
                                        String liveScore,
                                        String matchPhase,
                                        Long player1Id,
                                        String player1Name,
                                        Long player2Id,
                                        String player2Name,
                                        double decimalOddsPlayer1,
                                        double decimalOddsPlayer2,
                                        int americanOddsPlayer1,
                                        int americanOddsPlayer2,
                                        double impliedProbabilityPlayer1,
                                        double impliedProbabilityPlayer2,
                                        Double modelProbabilityPlayer1,
                                        Double modelProbabilityPlayer2,
                                        Double edgePlayer1,
                                        Double edgePlayer2,
                                        Integer modelFairAmericanOddsPlayer1,
                                        Integer modelFairAmericanOddsPlayer2,
                                        String suggestedSide,
                                        Double suggestedEdge,
                                        Integer suggestedFairAmericanOdds,
                                        Double confidenceLow,
                                        Double confidenceHigh,
                                        boolean recommended,
                                        String grade,
                                        String rationale,
                                        String topTrigger,
                                        Double topTriggerContribution,
                                        Double overallReliability,
                                        Double ratingAgreement,
                                        Double topTriggerReliability,
                                        Double suggestedSideBaselineStability,
                                        String matchupKey,
                                        String suggestedDedupeKey,
                                        String sourceType,
                                        Double sourceConfidence,
                                        String externalEventId,
                                        boolean displayed,
                                        boolean resulted,
                                        boolean matchCompleted,
                                        String sourceFeedCode,
                                        String sourceFeedEventId,
                                        String scoreDetail) {

    public LiveOddsRecommendationDto(String source,
                                     String strategy,
                                     String modelVersion,
                                     String eventName,
                                     String competitionName,
                                     boolean live,
                                     String startTimeIso,
                                     String liveScore,
                                     String matchPhase,
                                     Long player1Id,
                                     String player1Name,
                                     Long player2Id,
                                     String player2Name,
                                     double decimalOddsPlayer1,
                                     double decimalOddsPlayer2,
                                     int americanOddsPlayer1,
                                     int americanOddsPlayer2,
                                     double impliedProbabilityPlayer1,
                                     double impliedProbabilityPlayer2,
                                     Double modelProbabilityPlayer1,
                                     Double modelProbabilityPlayer2,
                                     Double edgePlayer1,
                                     Double edgePlayer2,
                                     Integer modelFairAmericanOddsPlayer1,
                                     Integer modelFairAmericanOddsPlayer2,
                                     String suggestedSide,
                                     Double suggestedEdge,
                                     Integer suggestedFairAmericanOdds,
                                     Double confidenceLow,
                                     Double confidenceHigh,
                                     boolean recommended,
                                     String grade,
                                     String rationale,
                                     String topTrigger,
                                     Double topTriggerContribution,
                                     String matchupKey,
                                     String suggestedDedupeKey) {
        this(
                source,
                strategy,
                modelVersion,
                eventName,
                competitionName,
                live,
                startTimeIso,
                liveScore,
                matchPhase,
                player1Id,
                player1Name,
                player2Id,
                player2Name,
                decimalOddsPlayer1,
                decimalOddsPlayer2,
                americanOddsPlayer1,
                americanOddsPlayer2,
                impliedProbabilityPlayer1,
                impliedProbabilityPlayer2,
                modelProbabilityPlayer1,
                modelProbabilityPlayer2,
                edgePlayer1,
                edgePlayer2,
                modelFairAmericanOddsPlayer1,
                modelFairAmericanOddsPlayer2,
                suggestedSide,
                suggestedEdge,
                suggestedFairAmericanOdds,
                confidenceLow,
                confidenceHigh,
                recommended,
                grade,
                rationale,
                topTrigger,
                topTriggerContribution,
                null,
                null,
                null,
                null,
                matchupKey,
                suggestedDedupeKey,
                null,
                null,
                null,
                true,
                false,
                false,
                null,
                null,
                null
        );
    }

    public LiveOddsRecommendationDto(String source,
                                     String strategy,
                                     String modelVersion,
                                     String eventName,
                                     String competitionName,
                                     boolean live,
                                     String startTimeIso,
                                     String liveScore,
                                     String matchPhase,
                                     Long player1Id,
                                     String player1Name,
                                     Long player2Id,
                                     String player2Name,
                                     double decimalOddsPlayer1,
                                     double decimalOddsPlayer2,
                                     int americanOddsPlayer1,
                                     int americanOddsPlayer2,
                                     double impliedProbabilityPlayer1,
                                     double impliedProbabilityPlayer2,
                                     Double modelProbabilityPlayer1,
                                     Double modelProbabilityPlayer2,
                                     Double edgePlayer1,
                                     Double edgePlayer2,
                                     Integer modelFairAmericanOddsPlayer1,
                                     Integer modelFairAmericanOddsPlayer2,
                                     String suggestedSide,
                                     Double suggestedEdge,
                                     Integer suggestedFairAmericanOdds,
                                     Double confidenceLow,
                                     Double confidenceHigh,
                                     boolean recommended,
                                     String grade,
                                     String rationale,
                                     String topTrigger,
                                     Double topTriggerContribution,
                                     Double overallReliability,
                                     Double ratingAgreement,
                                     Double topTriggerReliability,
                                     Double suggestedSideBaselineStability,
                                     String matchupKey,
                                     String suggestedDedupeKey) {
        this(
                source,
                strategy,
                modelVersion,
                eventName,
                competitionName,
                live,
                startTimeIso,
                liveScore,
                matchPhase,
                player1Id,
                player1Name,
                player2Id,
                player2Name,
                decimalOddsPlayer1,
                decimalOddsPlayer2,
                americanOddsPlayer1,
                americanOddsPlayer2,
                impliedProbabilityPlayer1,
                impliedProbabilityPlayer2,
                modelProbabilityPlayer1,
                modelProbabilityPlayer2,
                edgePlayer1,
                edgePlayer2,
                modelFairAmericanOddsPlayer1,
                modelFairAmericanOddsPlayer2,
                suggestedSide,
                suggestedEdge,
                suggestedFairAmericanOdds,
                confidenceLow,
                confidenceHigh,
                recommended,
                grade,
                rationale,
                topTrigger,
                topTriggerContribution,
                overallReliability,
                ratingAgreement,
                topTriggerReliability,
                suggestedSideBaselineStability,
                matchupKey,
                suggestedDedupeKey,
                null,
                null,
                null,
                true,
                false,
                false,
                null,
                null,
                null
        );
    }
}
