package com.ttl.tabletennis.dto;

import java.time.LocalDateTime;

public record PaperTradeBetDto(Long id,
                               String status,
                               String source,
                               String strategy,
                               String modelVersion,
                               String eventName,
                               String competitionName,
                               boolean liveAtPlacement,
                               String startTimeIso,
                               String externalEventId,
                               String player1Name,
                               String player2Name,
                               String sideName,
                               int americanOdds,
                               double decimalOdds,
                               double stake,
                               double potentialPayout,
                               Double profitLoss,
                               double modelProbability,
                               double impliedProbability,
                               double edge,
                               Double confidenceLow,
                               Double confidenceHigh,
                               String topTrigger,
                               Double topTriggerContribution,
                               String grade,
                               String rationale,
                               String lastObservedScore,
                               String lastObservedPhase,
                               String lastScoreSource,
                               Double lastScoreConfidence,
                               boolean lastObservationDisplayed,
                               boolean lastObservationResulted,
                               boolean lastMatchCompleted,
                               String lastSourceFeedCode,
                               String lastSourceFeedEventId,
                               String lastScoreDetail,
                               boolean trackedAfterClose,
                               String trackingState,
                               String settlementReason,
                               String settlementSource,
                               LocalDateTime lastObservedAt,
                               LocalDateTime placedAt,
                               LocalDateTime settledAt,
                               String eventKey,
                               String dedupeKey,
                               Long resultMatchId,
                               Long winnerPlayerId) {
}
